---
url: https://www.digglife.net
title : DiggLife
baseURL: https://www.digglife.net/
defaultContentLanguage: zh
language: zh
languageCode: zh
theme: ghostwriter
copyright: DiggLife
disqusShortname: digglifenet
weiboName: digglife
hasCJKLanguage: true
PygmentsCodeFences: true
pygmentsStyle: tango
MetaDataFormat: yaml
#uglyurls: true

Author:
  name: 摩摩诘
  profile: https://www.digglife.net

Taxonomies:
  tag: tags
  category: categories

Params:
  intro: false
  subtitle: 有关网络和软件技巧
  description: DiggLife 是一个有关互联网服务和实用软件技巧的博客
  headline:
  github: https://github.com/digglife
  linkedin: https://linkedin.com/in/digglife/
  stackoverflow: https://stackoverflow.com/users/1350657/zsl
  fanfou: http://fanfou.com/momojie
  psn: https://psnine.com/psnid/hajimuz
  baidutongji: b5322f4f14ea8094a32218bc1c34f770
  email: digglife@gmail.com
  weiboComment: true
  opengraph: true
  shareTwitter: true
  shareFacebook: true
  shareGooglePlus: true
  shareLinkedIn: true
  dateFormat: 2006-01-02

menu:
  main:
    - name: 首页
      url: "/"
      weight: 1
    - name: 关于
      url: "/about"
      weight: 2
    - name: 设备
      url: "/devices"
      weight: 2
